# Generated by Django 5.0.6 on 2024-12-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Christian', 'Christian'), ('Others', 'Others')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=11)),
                ('phone_office', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_residence', models.CharField(blank=True, max_length=15, null=True)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Others', 'Others')], max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
